# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20170328_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
