# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_disabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bithdate',
            new_name='birthdate',
        ),
    ]
